### ISSUE TITLE
NameError: name 'pcl_gt_1K_scaled' is not defined

### ISSUE THREAD

**Issue by ypzuo** [val-iisc/3d-lmnet#7]
Hi, I want use the evaluation to see the cd, emd etc. But it report the issue. I see some file but didn't find the detail. I miss something here?

**Comment by ypzuo** [comment]
I changed the parameter to 'pcl_gt_scaled', it worked. But another problem appeared, in the 'feed_dict={pcl_gt:batch_gt, img_inp:batch_ip}' showed the problem is 'ValueError: cannot feed value of shape(0,) for tensor u'pcl_gt:0',which has hsape '(24,1024,3) '
What should I do ?

**Comment by BS1396** [comment]
> I changed the parameter to 'pcl_gt_scaled', it worked. But another problem appeared, in the 'feed_dict={pcl_gt:batch_gt, img_inp:batch_ip}' showed the problem is 'ValueError: cannot feed value of shape(0,) for tensor u'pcl_gt:0',which has hsape '(24,1024,3) '
> What should I do ?

Hello, 
did u find the solution ?

**Comment by charliie-dev** [comment]
> I changed the parameter to 'pcl_gt_scaled', it worked. But another problem appeared, in the 'feed_dict={pcl_gt:batch_gt, img_inp:batch_ip}' showed the problem is 'ValueError: cannot feed value of shape(0,) for tensor u'pcl_gt:0',which has hsape '(24,1024,3) '
> What should I do ?

> > I changed the parameter to 'pcl_gt_scaled', it worked. But another problem appeared, in the 'feed_dict={pcl_gt:batch_gt, img_inp:batch_ip}' showed the problem is 'ValueError: cannot feed value of shape(0,) for tensor u'pcl_gt:0',which has hsape '(24,1024,3) '
> > What should I do ?
> 
> Hello,
> did u find the solution ?

Sorry for bothering,
Do you guys find any solution?

**Comment by charliie-dev** [comment]
I solve the above two problems' by changing lines: **282**,  **283**, **285**, **286**, **290** in `metrics.py`:
```
273: batches = len(train_pair_indices)
274: calculate_metrics(train_models, batches, pcl_gt_1K_scaled, reconstr_img_scaled, train_pair_indices)
276: batches = len(val_pair_indices)
277: calculate_metrics(val_models, batches, pcl_gt_1K_scaled, reconstr_img_scaled, val_pair_indices)
281: batches = len(models)
```
into
```
import math
273: batches = int(math.ceil(len(train_pair_indices) / BATCH_SIZE))
274: calculate_metrics(train_models, batches, pcl_gt_scaled, reconstr_img_scaled, train_pair_indices)
276: batches = int(math.ceil(len(val_pair_indices) / BATCH_SIZE))
277: calculate_metrics(val_models, batches, pcl_gt_scaled, reconstr_img_scaled, val_pair_indices)
281: batches = int(math.ceil(len(models) / BATCH_SIZE))
```
 - I think the author forgot to deal with batch size problems. It seems more reasonable to divide the length of the dataset with batch size since it later iterates through the **batches** in function: **calculate_metrics**.

 - As for changing **pcl_gt_1K_scaled** to **pcl_gt_scaled**, I'm not sure what the author's intention is here and how it would affect the performance. But at least the ***Evaluation*** part in README.md can run smoothly now.

If there is any misunderstanding of the code, please let me know. Thx!
